language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r sersue-springboot-webservice *
  - mkdir -p deploy
  - mv sersue-springboot-webservice.zip deploy/sersue-springboot-webservice.zip

deploy:
  - provider: s3 #s3에 접근해서 build파일 저장 해놓는 코드!
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: sersue-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sersue-springboot-build
    key: sersue-springboot-webservice.zip
    bundle_type: zip
    application : sersue-springboot-webservice
    deployment_group : sersue-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - msr56501354@gmail.com